blog/urls.py
from django.conf.urls import url
from blog.views import *

urlpatterns = [
    url(r'^$', PostLV.as_view(), name='index'),
    url(r'^post/$', PostLV.as_view(), name='post_list'),
    url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),

    url(r'^archive/$', PostAV.as_view(), name='post_archive'),
    url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/$', PostMAV.as_view(),
                                                name='post_month_archive'),
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$',
                                    PostDAV.as_view(), name='post_day_archive'),
    url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),

    # Example: /tag/
    url(r'^tag/$', TagTV.as_view(), name='tag_cloud'),

    # Example: /tag/tagname/
    url(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list'),

    # /search/
    url(r'^search/$', SearchFormView.as_view(), name='search'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf.urls.static import static
from django.conf import settings

from .views import HomeView

from .views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # url(r'^bookmark/$', BookMarkLV.as_view(), name='index'),
    # url(r'^bookmark/(?P<pk>\d+)/$', BookMarkDV.as_view(), name='detail')

    url(r'^$', HomeView.as_view(), name='home'),

    url(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
    url(r'^blog/', include('blog.urls', namespace='blog')),

    url(r'^photo/', include('photo.urls', namespace='photo')),

    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from __future__ import unicode_literals     # For python 2.x

from django.db import models
from django.utils.encoding import python_2_unicode_compatible

from django.core.urlresolvers import reverse

from tagging.fields import TagField

# Create your models here.


@python_2_unicode_compatible
class Post(models.Model):
    title = models.CharField('TITLE', max_length=100)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True,
                            help_text='one word for title alias')
    description = models.CharField('DESCRIPTION', max_length=100, blank=True,
                                   help_text='simple description text')
    content = models.TextField('CONTENT')

    tag = TagField()        # tagging 모듈의 자체 Field (Default max_length=255, Blank=True)

    create_date = models.DateTimeField('Create Date', auto_now_add=True)
    modify_date = models.DateTimeField('Modify Date', auto_now=True)


    class Meta: # 필드 속성 외 ORM 처리를 위해 필요한 파라메터 정의
        verbose_name = 'post'           # 단수 별칭
        verbose_name_plural = 'posts'   # 복수 별칭
        db_table = 'my_post'            # DB에 저장되는 실제 테이블 이름, 생략시 '앱명_모델클래스명'을 테이블 명으로 지정
        ordering = ('-modify_date',)    # 정렬기준 modify_date 내림차순

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.slug,))

    def get_previous_post(self):
        print("hear~!!! previous")
        return self.get_previous_by_modify_date()

    def get_next_post(self):
        print("hear~!!! next")
        return self.get_next_by_modify_date()

blog/forms.py
from django import forms

class PostSearchForm(forms.Form):
    search_word = forms.CharField(label="검색어")

blog/views.py
from django.db.models import Q
from django.shortcuts import render
from django.views.generic import ListView, DetailView, TemplateView, FormView
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView
from django.views.generic.dates import DayArchiveView, TodayArchiveView

from blog.models import Post
from .forms import PostSearchForm

from tagging.models import Tag, TaggedItem
from tagging.views import TaggedObjectList

class PostLV(ListView):
    model = Post
    template_name = 'blog/post_all.html'  # 템플릿 파일 이름 (default => blog/post_list.html)
    context_object_name = 'posts'     # default => object_list
    paginate_by = 2                   # 페이징 기능 / 한페이지에 2개씩


class PostDV(DetailView):
    model = Post


class PostAV(ArchiveIndexView):  # ArchiveIndexView : 객체에서 날짜 기준으로 출력
    model = Post
    date_field = 'modify_date'     # default template 이름은 '모델클래스소문자_archive.html'


class PostYAV(YearArchiveView):
    model = Post                # default template 이름은 '모델클래스소문자_archive_year.html'
    date_field = 'modify_date'  # 정렬의 기준이 되는 필드 'modify_date'
    make_object_list = True     # 해당 년도에 해당하는 객체의 리스트를 만들어 템플릿으로 전달한다.


class PostMAV(MonthArchiveView):
    model = Post
    date_field = 'modify_date'
    month_format = '%m'


class PostDAV(DayArchiveView):
    model = Post
    date_field = 'modify_date'


class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'modify_date'


class TagTV(TemplateView):
    template_name = "tagging/tagging_cloud.html"


class PostTOL(TaggedObjectList):
    model = Post
    template_name = 'tagging/tagging_post_list.html'


class SearchFormView(FormView):
    form_class = PostSearchForm
    template_name = 'blog/post_search.html'

    def form_valid(self, form):
        print("12312312312")
        schWord = '%s' % (self.request.POST['search_word'])

        post_list = Post.objects.filter(Q(title__icontains=schWord) |
                                        Q(description__icontains=schWord) |
                                        Q(content__icontains=schWord)).distinct()

        context = {}
        context['form'] = form
        context['search_term'] = schWord
        context['object_list'] = post_list

        return render(self.request, self.template_name, context)

blog/templates/blog/post_all.html
{% extends "base.html" %}

{% block title %}Django Blog {% endblock %}

{% block content %}
    <h1>Blog List</h1>
    {% for post in posts %}
        <h2><a href="{{ post.get_absolute_url }}"> {{ post.title }} </a></h2>
        {{ post.modify_date | date:"Y년 m월 d일" }}
        <p> {{ post.description }} </p>
    {% endfor %}

    <br>

    <div>
        <span>
            {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">Previous Page</a>
            {% endif %}

            [Page {{  page_obj.number }} of {{ page_obj.paginator.num_pages }}]

            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Next Page</a>
            {% endif %}
        </span>
    </div>

{#{%   for page in page_obj.paginator.object_list %}#}
{##}
{#    {{  page.count }}#}
{#{% endfor %}#}
{% endblock %}

blog/templates/blog/post_archive.html
{% extends "base.html" %}

{% block title %}Django Blog {% endblock %}

{% block content %}
    <h1>Post Archives util {% now "N d, Y" %} </h1>
    <ul>
        {% for date in date_list %}
        <li style="display: inline;">
            <a href="{% url 'blog:post_year_archive' date|date:'Y' %}">Year:{{ date|date:"Y" }}</a>
        </li>
        {% endfor %}
    </ul>
    <br>
    <div>
        <ul>
            {% for post in object_list %}
            <li> {{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;
                <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
            </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

blog/templates/blog/post_archive_day.html
{% extends "base.html" %}

{% block title %}Django Blog {% endblock %}

{% block content %}
    <h1>Post Archives for {{ day|date:'N d, Y' }} </h1>
    <h3>post_archive_day.html </h3>
    <ul>
        {% for post in object_list %}
        <li>
            {{ post.modify_date|date:"Y-m-d" }} &nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
        </li>
        {% endfor %}
    </ul>
{% endblock %}

blog/templates/blog/post_archive_month.html
{% extends "base.html" %}

{% block title %}Django Blog {% endblock %}

{% block content %}
    <h1>Post Archives for {{ month|date:'N, Y' }} </h1>
    <h3>post_archive_month.html </h3>
    <ul>
        {% for post in object_list %}
        <li>
            {{ post.modify_date|date:"Y-m-d" }} &nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
        </li>
        {% endfor %}
    </ul>
{% endblock %}

blog/templates/blog/post_archive_year.html
{% extends "base.html" %}

{% block title %}Django Blog {% endblock %}

{% block content %}
    <h1>Post Archives for {{ year|date:'Y' }} </h1>
    <h3>post_archive_year.html </h3>
    <ul>
        {% for date in date_list %}
        <li style="display: inline;">
            <a href="{% url 'blog:post_month_archive' year|date:'Y' date|date:'m' %}">{{ date|date:"F" }}</a>
        </li>
        {% endfor %}
    </ul>
    <br>
    <div>
        <ul>
            {% for post in object_list %}
            <li> {{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;
                <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
            </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "base.html" %}

{% block title %}Django Blog {% endblock %}

{% block content %}
<h2>{{ object.title }}</h2>
<p class="other_posts">
    {%  if object.get_next_by_modify_date %}
        <a href="{{ object.get_next_post.get_absolute_url }}" title="View next post">
        &laquo;-- {{object.get_next_post}}  </a></a>
        |||
    {% endif %}

    {% if object.get_previous_by_modify_date %}
    <a href="{{ object.get_previous_post.get_absolute_url }}" title="View previous">
        {{object.get_previous_post}} --&raquo;</a>
    {% endif %}
</p>

<p id="date">{{ object.modify_date | date:"Y년 m월 d일" }}</p>
<br>
<div class="body">
    {{ object.content|linebreaks }}
</div>

<div>
<b>TAGS: </b>
{% load tagging_tags %}
{% tags_for_object object as tags %}
{% for tag in tags %}
<a href="{% url 'blog:tagged_object_list' tag.name %}">{{tag.name}}</a>
{% endfor %}
<a href="{% url 'blog:tag_cloud' %}"><i>[ TagCloud ]</i></a>
</div>

    <br/>
    <div>
    {% load disqus_tags %}
    {% disqus_show_comments %}
    </div>


</div>



{% endblock %}

blog/templates/blog/post_search.html
{% extends "base.html" %}

{% block title %} post_search.html {% endblock %}

{% block content %}
    <div id="content">
    <h1>Blog Search</h1>

    <form action="." method="post">
        {% csrf_token %}
        {{ form.as_table }}
        <input type="submit" value="Submit">
    </form>

    <br/><br/>

    {% if object_list %}
    {%  for post in object_list %}
        <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
        {{ post.modify_date|date:'N d, Y' }}`
        <p>{{ post.description }}</p>
    {% endfor %}

    {% elif search_term %}

        <b><i>Search Word({{ search_term }}) Not Found !! </i></b>
    {% endif %}

    </div>
{% endblock%}