blog/urls.py
from django.conf.urls import url
from blog.views import *

urlpatterns = [
    url(r'^$', PostLV.as_view(), name='index'),
    url(r'^post/$', PostLV.as_view(), name='post_list'),
    url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),

    url(r'^archive/$', PostAV.as_view(), name='post_archive'),
    url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/$', PostMAV.as_view(),
                                                name='post_month_archive'),
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$',
                                    PostDAV.as_view(), name='post_day_archive'),
    url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),

    # Example: /tag/
    url(r'^tag/$', TagTV.as_view(), name='tag_cloud'),

    # Example: /tag/tagname/
    url(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list'),

    # /search/
    url(r'^search/$', SearchFormView.as_view(), name='search'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf.urls.static import static
from django.conf import settings

from .views import HomeView

from .views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # url(r'^bookmark/$', BookMarkLV.as_view(), name='index'),
    # url(r'^bookmark/(?P<pk>\d+)/$', BookMarkDV.as_view(), name='detail')

    url(r'^$', HomeView.as_view(), name='home'),

    url(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
    url(r'^blog/', include('blog.urls', namespace='blog')),

    url(r'^photo/', include('photo.urls', namespace='photo')),

    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [

    url(r'^$', AlbumLV.as_view(), name='index'),
    url(r'^album/$', AlbumLV.as_view, name='album_list'),
    url(r'^album/(?P<pk>\d+)/$', AlbumDV.as_view(), name='album_detail'),
    url(r'^photo/(?P<pk>\d+)/$', PhotoDV.as_view(), name='photo_detail'),
]

photo/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models

from django.core.urlresolvers import reverse
from .fields import ThumbnailImageField


@python_2_unicode_compatible
class Album(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField('One Line Description', max_length=100, blank=True)

    class Meta:
        db_table = 'my_album'
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('photo:album_detail', args=(self.id, ))


@python_2_unicode_compatible
class Photo(models.Model):
    album = models.ForeignKey(Album)
    title = models.CharField(max_length=50)
    image = ThumbnailImageField(upload_to='photo/%Y/%m')
    description = models.TextField('Photo Description', blank=True)
    upload_date = models.DateTimeField('upload Date', auto_now_add=True)

    class Meta:
        db_table = 'my_photo'
        ordering = ['title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('photo:photo_detail', args=(self.id,))

photo/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from .models import Album, Photo


class AlbumLV(ListView):
    model = Album


class AlbumDV(DetailView):
    model = Album


class PhotoDV(DetailView):
    model = Photo

photo/templates/photo/album_detail.html
{% extends "base.html" %}

{% block title %}album_detail.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "photo/photo.css" %}{% endblock %}

{% block content %}
<div id="content">

    <h2 style="display:inline">{{ object.name }}</h2>
    &emsp;<b><i>{{ object.description }}</i></b>

    <hr/>

    <div class="album-detail">
        {% for photo in object.photo_set.all %}
        <div class="album-detail-photo">
            <a href="{{ photo.get_absolute_url }}">
            <img class="thumbnail" src="{{ photo.image.thumb_url }}" />
            </a>
            <li>{{ photo.title }}</li>
            <li>{{ photo.upload_date|date:"Y-m-d" }}</li>
        </div>
        {% endfor %}
    </div>

</div>
{% endblock %}

photo/templates/photo/album_list.html
{% extends "base.html" %}

{% block title %}album_list.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "photo/photo.css" %}{% endblock %}

{% block content %}
<div id="content">

    {% for item in object_list %}

    <div class="clear_float">
        <h2 style="display:inline"><a href="{% url 'photo:album_detail' item.id %}">{{ item.name }}</a></h2>
        &emsp;<b><i>{{ item.description }}</i></b>
    </div>

    <hr/>

    <div class="album-list">
        {% for photo in item.photo_set.all|slice:":5" %}
        <div class="album-list-photo">
            <a href="{{ photo.get_absolute_url }}">
            <img class="thumbnail" src="{{ photo.image.thumb_url }}" />
            </a>
        </div>
        {% endfor %}
    </div>

    {% endfor %}

</div>
{% endblock %}

photo/templates/photo/photo_detail.html
{% extends "base.html" %}

{% block title %}photo_detail.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "photo/photo.css" %}{% endblock %}

{% block content %}
<div id="content">

    <h2>{{ object.title }}</h2>
    
    <table class="photo-detail">
    <tr>
    <td>
        <a href="{{ object.image.url }}">
        <img style="max-width:100%" src="{{ object.image.url }}" />
        </a>
    </td>
    
    <td>
    <ul>
        <li>Photo Description</li>
        {% if object.description %}<p>{{ object.description|linebreaks }}</p>
        {% else %}<p>(blank)</p>{% endif %}
        <li>Date Uploaded</li>
        <p>{{ object.upload_date }}</p>
        <li>Album Name</li>
        <p><a href="{% url 'photo:album_detail' object.album.id %}">{{ object.album.name }}</a></p>
    </ul>
    </td>
    </tr></table>

</div>
{% endblock %}